// Gem data: facts written for a 6-year-old.
// cut: natural crystal habit | fx: surface pattern | refract: multi-bounce shader params
// material: MeshPhysicalMaterial params (also the fallback when the HDRI can't load)
export const GEMS = [
  {
    id: 'obsidian', name: 'Black Obsidian', emoji: '🌋', pronounce: 'ob-SID-ee-un',
    accent: '#3dd68c', swatch: ['#3b3f46', '#101216', '#000000'],
    cut: 'chunk', fx: { type: 'ripple' },
    material: {
      color: 0x050507, roughness: 0.08, metalness: 0.0,
      transmission: 0.12, ior: 1.5, thickness: 2.2,
      clearcoat: 1.0, clearcoatRoughness: 0.04,
      attenuationColor: 0x16241a, attenuationDistance: 0.7, envMapIntensity: 0.45,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '5 out of 10' },
      { icon: '🌋', label: 'What is it?', value: 'Volcano glass!' },
      { icon: '🗺️', label: 'Found in', value: 'Mexico, Iceland & the USA' },
      { icon: '🎨', label: 'Color', value: 'Shiny black' },
    ],
    story: 'Black Obsidian is nature’s glass! When a volcano erupts, super-hot lava sometimes cools down SO fast that it freezes into shiny black glass before any crystals can grow.',
    wow: 'Obsidian can be sharper than a doctor’s scalpel! Long, long ago, people made arrowheads and knives out of it.',
  },
  {
    id: 'diamond', name: 'Diamond', emoji: '💎', pronounce: 'DY-mund',
    accent: '#bfe3ff', swatch: ['#ffffff', '#cfe8ff', '#8fb8e8'],
    cut: 'octa',
    refract: { color: '#ffffff', ior: 2.42, aberration: 0.035, fresnel: 0.25, bounces: 3 },
    material: { color: 0xffffff, roughness: 0.0, transmission: 1.0, ior: 2.42, thickness: 1.6, envMapIntensity: 1.8 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '10 out of 10 — the champ!' },
      { icon: '🎂', label: 'Birthstone', value: 'April' },
      { icon: '🗺️', label: 'Found in', value: 'Deep, deep underground' },
      { icon: '🎨', label: 'Color', value: 'Clear like ice' },
    ],
    story: 'Diamond is the hardest natural thing on Earth! It grows super deep underground where it is very hot and very squished, and volcanoes carry it up to us.',
    wow: 'Diamonds are made of the exact same stuff as a pencil tip — carbon! Squeezing it for billions of years makes it sparkly instead of scribbly.',
  },
  {
    id: 'ruby', name: 'Ruby', emoji: '❤️', pronounce: 'ROO-bee',
    accent: '#ff4d6d', swatch: ['#ff7a93', '#e6173f', '#7c0220'],
    cut: 'hexTab',
    refract: { color: '#ff3852', ior: 1.77, aberration: 0.012, fresnel: 0.15, bounces: 3 },
    material: { color: 0xff4060, roughness: 0.02, transmission: 0.95, ior: 1.77, thickness: 1.8, envMapIntensity: 1.5 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '9 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'July' },
      { icon: '🗺️', label: 'Found in', value: 'Myanmar, Thailand & Africa' },
      { icon: '🎨', label: 'Color', value: 'Fire-engine red' },
    ],
    story: 'Ruby is the king of red gems! A tiny pinch of an ingredient called chromium sneaks inside and paints the whole crystal red.',
    wow: 'Rubies and sapphires are secretly the SAME mineral. If it’s red, we call it a ruby. Any other color? That’s a sapphire!',
  },
  {
    id: 'sapphire', name: 'Sapphire', emoji: '💙', pronounce: 'SAF-ire',
    accent: '#4d7cff', swatch: ['#7da2ff', '#1f4fd8', '#0a1f6b'],
    cut: 'bipyramid',
    refract: { color: '#3c66ff', ior: 1.77, aberration: 0.012, fresnel: 0.15, bounces: 3 },
    material: { color: 0x3f6fff, roughness: 0.02, transmission: 0.95, ior: 1.77, thickness: 1.8, envMapIntensity: 1.5 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '9 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'September' },
      { icon: '🗺️', label: 'Found in', value: 'Sri Lanka, Australia & Montana' },
      { icon: '🎨', label: 'Color', value: 'Deep ocean blue' },
    ],
    story: 'Sapphire is ruby’s blue brother! It is so tough that some watch glass and even spaceship windows are made from grown sapphire.',
    wow: 'Sapphires come in almost EVERY color — blue, pink, yellow, green, even rainbow party colors. Every color except red!',
  },
  {
    id: 'emerald', name: 'Emerald', emoji: '💚', pronounce: 'EM-er-uld',
    accent: '#19c37d', swatch: ['#4fe3a4', '#0ca860', '#03522d'],
    cut: 'hexColumn',
    refract: { color: '#18c578', ior: 1.57, aberration: 0.008, fresnel: 0.12, bounces: 3 },
    material: { color: 0x17b06b, roughness: 0.03, transmission: 0.92, ior: 1.57, thickness: 2.0, envMapIntensity: 0.9 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'May' },
      { icon: '🗺️', label: 'Found in', value: 'Colombia, Zambia & Brazil' },
      { icon: '🎨', label: 'Color', value: 'Jungle green' },
    ],
    story: 'Emerald is the green superstar of gems. It grows slowly in cracks deep in the mountains, and people have treasured it for thousands of years.',
    wow: 'Most emeralds have a tiny “garden” inside — little squiggly marks that prove the gem grew all by itself in nature!',
  },
  {
    id: 'amethyst', name: 'Amethyst', emoji: '💜', pronounce: 'AM-uh-thist',
    accent: '#a06bff', swatch: ['#c79bff', '#8a4dff', '#3d1680'],
    cut: 'cluster',
    material: {
      emissive: 0x7a3df0, emissiveIntensity: 0.32,
      color: 0xa570ff, roughness: 0.05, transmission: 0.92, ior: 1.55, thickness: 1.8,
      attenuationColor: 0x8a4dff, attenuationDistance: 2.6,
      clearcoat: 0.4, clearcoatRoughness: 0.1, envMapIntensity: 1.4,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'February' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil & Uruguay' },
      { icon: '🎨', label: 'Color', value: 'Royal purple' },
    ],
    story: 'Amethyst is purple quartz that grows in pointy crystal towers. It loves to grow inside hollow rocks, packed together like a crystal city.',
    wow: 'Amethyst grows inside secret rocks called geodes — boring and bumpy on the outside, but crack one open and it’s FULL of purple crystals!',
  },
  {
    id: 'citrine', name: 'Citrine', emoji: '🍋', pronounce: 'SIH-treen',
    accent: '#ffb321', swatch: ['#ffd97a', '#ff9d1f', '#9c5400'],
    cut: 'point',
    refract: { color: '#ffa226', ior: 1.55, aberration: 0.008, fresnel: 0.12, bounces: 3 },
    material: { color: 0xffa01f, roughness: 0.04, transmission: 0.95, ior: 1.55, thickness: 1.8, envMapIntensity: 1.4 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'November' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil' },
      { icon: '🎨', label: 'Color', value: 'Sunny gold' },
    ],
    story: 'Citrine is amethyst’s sunny cousin — the same crystal, but heated up until it turns golden like honey and sunshine.',
    wow: 'Citrine is named after “citron”, the French word for lemon, because it looks like frozen lemonade!',
  },
  {
    id: 'rosequartz', name: 'Rose Quartz', emoji: '🌸', pronounce: 'rohz KWORTS',
    accent: '#ff9ec7', swatch: ['#ffd2e4', '#ff9ec7', '#c75e8e'],
    cut: 'rough', fx: { type: 'cloudy' },
    material: {
      emissive: 0xc4647e, emissiveIntensity: 0.12,
      color: 0xffb3cf, roughness: 0.35, transmission: 0.85, ior: 1.55, thickness: 2.6,
      attenuationColor: 0xff9ec7, attenuationDistance: 1.2,
      clearcoat: 0.8, clearcoatRoughness: 0.2, envMapIntensity: 1.2,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '💗', label: 'Known as', value: 'The friendship stone' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil, Madagascar & South Dakota' },
      { icon: '🎨', label: 'Color', value: 'Soft pink' },
    ],
    story: 'Rose Quartz is a soft pink, cloudy crystal. People all over the world call it the stone of friendship and kind hearts.',
    wow: 'Some special rose quartz hides a glowing six-pointed STAR inside that only appears when light shines on it just right!',
  },
  {
    id: 'opal', name: 'Opal', emoji: '🌈', pronounce: 'OH-pul',
    accent: '#7fe8e0', swatch: ['#ffffff', '#bdf3ec', '#caa6ff'],
    cut: 'nodule', fx: { type: 'flecks' },
    material: {
      color: 0xf2f6f5, roughness: 0.18, transmission: 0.5, ior: 1.45, thickness: 2.4,
      attenuationColor: 0xd9fff7, attenuationDistance: 1.5,
      iridescence: 1.0, iridescenceIOR: 1.3, iridescenceThicknessRange: [120, 700],
      clearcoat: 1.0, clearcoatRoughness: 0.15, envMapIntensity: 1.3,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '6 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'October' },
      { icon: '🗺️', label: 'Found in', value: 'Australia (almost all of them!)' },
      { icon: '🎨', label: 'Color', value: 'Rainbow flashes' },
    ],
    story: 'Opal is the rainbow gem! It is made from tiny, tiny balls of silica with real water trapped inside, and they bounce light into every color you can imagine.',
    wow: 'NASA robots found opal on MARS! And every opal has a little bit of real water inside it.',
  },
  {
    id: 'clearquartz', name: 'Clear Quartz', emoji: '🔮', pronounce: 'kleer KWORTS',
    accent: '#dfe9f5', swatch: ['#ffffff', '#dfe9f5', '#9fb3c8'],
    cut: 'point',
    refract: { color: '#f2f7ff', ior: 1.55, aberration: 0.006, fresnel: 0.2, bounces: 3 },
    material: { color: 0xf2f7ff, roughness: 0.03, transmission: 0.97, ior: 1.55, thickness: 1.8, envMapIntensity: 1.4 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '⏰', label: 'Super power', value: 'Keeps time in clocks!' },
      { icon: '🗺️', label: 'Found in', value: 'Everywhere on Earth!' },
      { icon: '🎨', label: 'Color', value: 'Clear like ice water' },
    ],
    story: 'Clear Quartz is the most famous crystal of all, and it grows in sharp six-sided towers. It is one of the most common minerals on the whole planet!',
    wow: 'There is probably quartz in your house RIGHT NOW — tiny quartz crystals vibrate millions of times a second to keep time inside clocks and watches!',
  },
  {
    id: 'smokyquartz', name: 'Smoky Quartz', emoji: '🌫️', pronounce: 'SMOH-kee KWORTS',
    accent: '#b08d62', swatch: ['#c9a87c', '#7a5c3d', '#332313'],
    cut: 'point',
    refract: { color: '#a3805c', ior: 1.55, aberration: 0.006, fresnel: 0.15, bounces: 3 },
    material: { color: 0x8a6a4a, roughness: 0.04, transmission: 0.9, ior: 1.55, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🏴', label: 'Famous as', value: 'Scotland’s national gem' },
      { icon: '🗺️', label: 'Found in', value: 'Scotland, the Alps & Colorado' },
      { icon: '🎨', label: 'Color', value: 'Smoky brown' },
    ],
    story: 'Smoky Quartz looks like it has campfire smoke frozen inside! It gets its brown color from natural energy in the rocks deep underground.',
    wow: 'In Scotland it is called Cairngorm, and people have put it on the handles of fancy Scottish daggers for hundreds of years!',
  },
  {
    id: 'tigerseye', name: 'Tiger’s Eye', emoji: '🐯', pronounce: 'TY-gerz eye',
    accent: '#d99021', swatch: ['#ffc04d', '#a8651a', '#4d2c08'],
    cut: 'rough', fx: { type: 'stripes', colors: ['#8a4b12', '#d99021', '#5c300a', '#ffc04d', '#6e3c0d'] },
    material: { color: 0xffffff, roughness: 0.32, metalness: 0.1, clearcoat: 0.8, clearcoatRoughness: 0.25, envMapIntensity: 1.1 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🐈', label: 'Super power', value: 'Flashes like a cat’s eye' },
      { icon: '🗺️', label: 'Found in', value: 'South Africa & Australia' },
      { icon: '🎨', label: 'Color', value: 'Gold & brown stripes' },
    ],
    story: 'Tiger’s Eye is striped gold and brown like a tiger’s fur. Tiny shiny fibers inside catch the light and make a glowing stripe that moves when you turn it!',
    wow: 'That moving flash is called “chatoyancy” — the same trick that makes a cat’s eye glow at night!',
  },
  {
    id: 'agate', name: 'Agate', emoji: '🪨', pronounce: 'AG-it',
    accent: '#d9a05c', swatch: ['#f0e0cc', '#c98a4a', '#7a4a26'],
    cut: 'nodule', fx: { type: 'rings', colors: ['#8a5a33', '#d9b38c', '#f0e0cc', '#a87444', '#c98a4a'] },
    material: { color: 0xffffff, roughness: 0.25, transmission: 0.15, thickness: 1.5, clearcoat: 0.9, clearcoatRoughness: 0.15, envMapIntensity: 1.1 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🫧', label: 'Where it grows', value: 'Inside lava bubbles!' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil, Mexico & the USA' },
      { icon: '🎨', label: 'Color', value: 'Striped rainbow bands' },
    ],
    story: 'Agate grows inside empty bubbles in old lava, painting stripe after stripe of color as it fills the bubble up over millions of years.',
    wow: 'Slice an agate open and you can count its rings — just like counting tree rings!',
  },
  {
    id: 'carnelian', name: 'Carnelian', emoji: '🔥', pronounce: 'kar-NEEL-yun',
    accent: '#ff7a3c', swatch: ['#ffa05c', '#e65c1f', '#8a2e08'],
    cut: 'nodule',
    material: { color: 0xe65c1f, roughness: 0.2, transmission: 0.45, ior: 1.54, thickness: 2.0, attenuationColor: 0xd9531a, attenuationDistance: 1.2, clearcoat: 0.8, clearcoatRoughness: 0.15, envMapIntensity: 1.2 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🏺', label: 'Loved by', value: 'Ancient Egyptian pharaohs' },
      { icon: '🗺️', label: 'Found in', value: 'India, Brazil & Egypt' },
      { icon: '🎨', label: 'Color', value: 'Sunset orange' },
    ],
    story: 'Carnelian glows like a little piece of sunset. Ancient Egyptians believed it carried the power of the sun and carved it into rings and amulets.',
    wow: 'King Tut was buried with carnelian treasures over 3,000 years ago — and they are still glowing orange today!',
  },
  {
    id: 'onyx', name: 'Onyx', emoji: '🖤', pronounce: 'ON-iks',
    accent: '#cfcfcf', swatch: ['#3a3a3a', '#0d0d0d', '#000000'],
    cut: 'rough', fx: { type: 'stripes', colors: ['#0d0d0d', '#101010', '#e8e8e8', '#0d0d0d', '#141414'] },
    material: { color: 0xffffff, roughness: 0.18, clearcoat: 1.0, clearcoatRoughness: 0.1, envMapIntensity: 1.0 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🦓', label: 'Special look', value: 'Black with white stripes' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil, India & Uruguay' },
      { icon: '🎨', label: 'Color', value: 'Midnight black' },
    ],
    story: 'Onyx is agate’s mysterious cousin — deep black stone with crisp white stripes running through it like zebra patterns.',
    wow: 'Ancient Romans carved tiny pictures into onyx stripes so the white picture popped out of the black background — the first cameos!',
  },
  {
    id: 'jasper', name: 'Jasper', emoji: '🏜️', pronounce: 'JAS-per',
    accent: '#c96a3a', swatch: ['#d98a52', '#a04a28', '#5c2412'],
    cut: 'rough', fx: { type: 'spots', bg: '#a04a28', colors: ['#7a2e16', '#c96a3a', '#5c1f0e', '#d9a05c'], count: 70, rMin: 8, rMax: 38 },
    material: { color: 0xffffff, roughness: 0.45, clearcoat: 0.5, clearcoatRoughness: 0.3, envMapIntensity: 0.9 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🖼️', label: 'Special look', value: 'Patterns like tiny paintings' },
      { icon: '🗺️', label: 'Found in', value: 'All over the world' },
      { icon: '🎨', label: 'Color', value: 'Desert red & brown' },
    ],
    story: 'Jasper is the storyteller stone — every piece has different spots, stripes and swirls, like a tiny painting of a desert or a beach.',
    wow: 'Some jasper, called “picture jasper”, has patterns that look exactly like little landscape paintings made by the Earth itself!',
  },
  {
    id: 'aventurine', name: 'Aventurine', emoji: '🍀', pronounce: 'ah-VEN-chur-een',
    accent: '#3cb371', swatch: ['#6fd49a', '#2e9960', '#145c36'],
    cut: 'rough',
    material: { color: 0x2e9960, roughness: 0.3, transmission: 0.3, ior: 1.55, thickness: 2.0, attenuationColor: 0x2e9960, attenuationDistance: 1.5, clearcoat: 0.7, clearcoatRoughness: 0.2, envMapIntensity: 1.1 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '✨', label: 'Super power', value: 'Glitters with tiny sparkles' },
      { icon: '🗺️', label: 'Found in', value: 'India & Brazil' },
      { icon: '🎨', label: 'Color', value: 'Lucky green' },
    ],
    story: 'Aventurine is green quartz filled with millions of tiny mirror flakes. Tip it in the light and the whole stone glitters!',
    wow: 'That glitter effect has its own fancy name — “aventurescence” — and people call aventurine the luckiest stone of all!',
  },
  {
    id: 'chrysoprase', name: 'Chrysoprase', emoji: '🍏', pronounce: 'KRIS-oh-prayz',
    accent: '#66d98a', swatch: ['#8ae6a8', '#3fbf6f', '#1a7a42'],
    cut: 'nodule',
    material: { color: 0x3fbf6f, roughness: 0.22, transmission: 0.45, ior: 1.54, thickness: 2.0, attenuationColor: 0x35b364, attenuationDistance: 1.3, clearcoat: 0.8, clearcoatRoughness: 0.15, envMapIntensity: 1.1 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🧪', label: 'Secret recipe', value: 'Nickel makes it green' },
      { icon: '🗺️', label: 'Found in', value: 'Australia' },
      { icon: '🎨', label: 'Color', value: 'Apple green' },
    ],
    story: 'Chrysoprase looks like a green apple turned into stone! A sprinkle of nickel gives it that juicy minty color.',
    wow: 'Alexander the Great supposedly wore chrysoprase into battle — and a king of Prussia loved it so much he covered a whole palace room with it!',
  },
  {
    id: 'bloodstone', name: 'Bloodstone', emoji: '🛡️', pronounce: 'BLUD-stohn',
    accent: '#2e8b57', swatch: ['#3fa06b', '#1d4a2a', '#b3202a'],
    cut: 'rough', fx: { type: 'spots', bg: '#1d4a2a', colors: ['#b3202a', '#8a1620', '#16381f'], count: 45, rMin: 6, rMax: 22 },
    material: { color: 0xffffff, roughness: 0.4, clearcoat: 0.6, clearcoatRoughness: 0.25, envMapIntensity: 0.9 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'March (the old one!)' },
      { icon: '🗺️', label: 'Found in', value: 'India & Australia' },
      { icon: '🎨', label: 'Color', value: 'Dark green, red speckles' },
    ],
    story: 'Bloodstone is a dark green warrior stone speckled with bright red dots of iron. Ancient soldiers carried it as a good-luck charm for bravery.',
    wow: 'Its old Greek name is “heliotrope”, which means sun-turner — people believed it could make the sun look red!',
  },
  {
    id: 'aquamarine', name: 'Aquamarine', emoji: '🌊', pronounce: 'ah-kwa-ma-REEN',
    accent: '#79d4e8', swatch: ['#aef0fa', '#5cc4dd', '#1d7a99'],
    cut: 'hexColumn',
    refract: { color: '#8fdcec', ior: 1.58, aberration: 0.008, fresnel: 0.18, bounces: 3 },
    material: { color: 0x79d4e8, roughness: 0.03, transmission: 0.95, ior: 1.58, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'March' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil, Pakistan & Africa' },
      { icon: '🎨', label: 'Color', value: 'Sea blue' },
    ],
    story: 'Aquamarine means “water of the sea” — and it really looks like a piece of clean ocean turned into crystal. It is emerald’s blue cousin!',
    wow: 'Sailors used to carry aquamarine as a lucky charm for safe voyages. One found in Brazil, the Dom Pedro, is as big as a fire hydrant!',
  },
  {
    id: 'morganite', name: 'Morganite', emoji: '🍑', pronounce: 'MOR-gan-ite',
    accent: '#ffb3c4', swatch: ['#ffd4de', '#ff9fb5', '#c75e7a'],
    cut: 'hexColumn',
    refract: { color: '#ffc2cf', ior: 1.58, aberration: 0.007, fresnel: 0.18, bounces: 3 },
    material: { color: 0xffb3c4, roughness: 0.03, transmission: 0.95, ior: 1.58, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '👨‍👩‍👧', label: 'Family', value: 'Emerald’s pink cousin' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil & Madagascar' },
      { icon: '🎨', label: 'Color', value: 'Peachy pink' },
    ],
    story: 'Morganite is a peachy-pink crystal from the same family as emerald and aquamarine. A dash of manganese gives it that soft sunset color.',
    wow: 'It is named after J.P. Morgan, a famous banker who collected so many gems that museums named this one after him!',
  },
  {
    id: 'heliodor', name: 'Heliodor', emoji: '☀️', pronounce: 'HEE-lee-oh-dor',
    accent: '#ffd84d', swatch: ['#ffe98a', '#ffd234', '#b8930d'],
    cut: 'hexColumn',
    refract: { color: '#ffdf66', ior: 1.58, aberration: 0.007, fresnel: 0.18, bounces: 3 },
    material: { color: 0xffd84d, roughness: 0.03, transmission: 0.95, ior: 1.58, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '🌞', label: 'Name means', value: '“Gift of the sun”' },
      { icon: '🗺️', label: 'Found in', value: 'Ukraine, Brazil & Namibia' },
      { icon: '🎨', label: 'Color', value: 'Golden sunshine' },
    ],
    story: 'Heliodor’s name means “gift of the sun” in Greek — a golden-yellow crystal from the emerald family that looks like trapped sunlight.',
    wow: 'Emerald, aquamarine, morganite and heliodor are all the SAME mineral, beryl — just wearing different color costumes!',
  },
  {
    id: 'redberyl', name: 'Red Beryl', emoji: '🚨', pronounce: 'red BAIR-ul',
    accent: '#ff2e44', swatch: ['#ff6b7d', '#e0112a', '#7a0413'],
    cut: 'hexColumn',
    refract: { color: '#ff3349', ior: 1.58, aberration: 0.008, fresnel: 0.15, bounces: 3 },
    material: { color: 0xe0112a, roughness: 0.03, transmission: 0.92, ior: 1.58, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '🦄', label: 'How rare?', value: 'Rarer than diamond!' },
      { icon: '🗺️', label: 'Found in', value: 'Only Utah, USA!' },
      { icon: '🎨', label: 'Color', value: 'Raspberry red' },
    ],
    story: 'Red Beryl is one of the rarest gems on the whole planet. Gem-quality crystals are found in just ONE place: the Wah Wah Mountains of Utah.',
    wow: 'For every 150,000 diamonds dug up, only ONE red beryl is found. That makes it thousands of times rarer than diamond!',
  },
  {
    id: 'padparadscha', name: 'Padparadscha', emoji: '🪷', pronounce: 'pad-pa-RAD-sha',
    accent: '#ff9e80', swatch: ['#ffc4ae', '#ff8a66', '#c2492a'],
    cut: 'bipyramid',
    refract: { color: '#ffa888', ior: 1.77, aberration: 0.012, fresnel: 0.15, bounces: 3 },
    material: { color: 0xff9e80, roughness: 0.02, transmission: 0.95, ior: 1.77, thickness: 1.8, envMapIntensity: 1.4 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '9 out of 10' },
      { icon: '🌅', label: 'Name means', value: '“Lotus flower” color' },
      { icon: '🗺️', label: 'Found in', value: 'Sri Lanka' },
      { icon: '🎨', label: 'Color', value: 'Pink-orange sunset' },
    ],
    story: 'Padparadscha is the rarest sapphire of all — not blue, but a magical mix of pink AND orange at the same time, like a tropical sunset.',
    wow: 'Its tongue-twister name means “lotus blossom” in the Sinhala language of Sri Lanka. Try saying it five times fast!',
  },
  {
    id: 'garnet', name: 'Garnet', emoji: '🍒', pronounce: 'GAR-net',
    accent: '#d42a3f', swatch: ['#f06a7a', '#b3142b', '#590713'],
    cut: 'dodeca',
    refract: { color: '#d42a3f', ior: 1.74, aberration: 0.01, fresnel: 0.15, bounces: 3 },
    material: { color: 0xb3142b, roughness: 0.03, transmission: 0.9, ior: 1.74, thickness: 1.8, envMapIntensity: 1.4 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'January' },
      { icon: '🗺️', label: 'Found in', value: 'Africa, India & the USA' },
      { icon: '🎨', label: 'Color', value: 'Cherry red' },
    ],
    story: 'Garnet grows in amazing ball-like crystals with twelve diamond-shaped faces — nature builds that shape all by itself!',
    wow: 'Garnet is named after pomegranate seeds, because little red garnet crystals look just like the juicy seeds inside the fruit!',
  },
  {
    id: 'tsavorite', name: 'Tsavorite', emoji: '🦁', pronounce: 'SAV-oh-rite',
    accent: '#1fc46a', swatch: ['#5fe39a', '#15a857', '#06532a'],
    cut: 'dodeca',
    refract: { color: '#1fc46a', ior: 1.74, aberration: 0.01, fresnel: 0.15, bounces: 3 },
    material: { color: 0x15a857, roughness: 0.03, transmission: 0.9, ior: 1.74, thickness: 1.8, envMapIntensity: 1.4 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🦁', label: 'Named after', value: 'Tsavo, land of lions' },
      { icon: '🗺️', label: 'Found in', value: 'Kenya & Tanzania' },
      { icon: '🎨', label: 'Color', value: 'Bright lion-grass green' },
    ],
    story: 'Tsavorite is garnet’s brilliant green brother, discovered near Tsavo National Park in Kenya — a place famous for its lions!',
    wow: 'Tsavorite was only discovered in 1967 — your grandparents were probably already alive when this gem was found!',
  },
  {
    id: 'bluetopaz', name: 'Blue Topaz', emoji: '🧊', pronounce: 'blue TOH-paz',
    accent: '#4db8ff', swatch: ['#9ed9ff', '#3aa0e8', '#0d5c99'],
    cut: 'orthoPrism',
    refract: { color: '#66c4ff', ior: 1.62, aberration: 0.009, fresnel: 0.18, bounces: 3 },
    material: { color: 0x4db8ff, roughness: 0.02, transmission: 0.95, ior: 1.62, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'December' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil & Texas' },
      { icon: '🎨', label: 'Color', value: 'Icy sky blue' },
    ],
    story: 'Blue Topaz grows in long crystal columns with a wedge-shaped tip, like nature’s own ice pop. It is the state gem of Texas!',
    wow: 'Topaz crystals can grow GIGANTIC — some weigh more than a whole car! One museum crystal is over 600 pounds.',
  },
  {
    id: 'imperialtopaz', name: 'Imperial Topaz', emoji: '👑', pronounce: 'im-PEER-ee-ul TOH-paz',
    accent: '#ffae42', swatch: ['#ffd285', '#ff9d2e', '#b35e08'],
    cut: 'orthoPrism',
    refract: { color: '#ffb44d', ior: 1.62, aberration: 0.009, fresnel: 0.15, bounces: 3 },
    material: { color: 0xffae42, roughness: 0.02, transmission: 0.95, ior: 1.62, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'November' },
      { icon: '🗺️', label: 'Found in', value: 'Ouro Preto, Brazil' },
      { icon: '🎨', label: 'Color', value: 'Golden honey-orange' },
    ],
    story: 'Imperial Topaz is the royal version of topaz — a glowing golden-orange crystal named to honor emperors of Russia and Brazil.',
    wow: 'Almost ALL the imperial topaz in the world comes from mines around one single town in Brazil called Ouro Preto — “Black Gold”!',
  },
  {
    id: 'greentourmaline', name: 'Green Tourmaline', emoji: '🥒', pronounce: 'TOOR-ma-leen',
    accent: '#1faa59', swatch: ['#5ed98f', '#179148', '#063d1e'],
    cut: 'trigonal',
    refract: { color: '#23b362', ior: 1.62, aberration: 0.009, fresnel: 0.15, bounces: 3 },
    material: { color: 0x179148, roughness: 0.03, transmission: 0.92, ior: 1.62, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'October (with opal!)' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil, Africa & Maine' },
      { icon: '🎨', label: 'Color', value: 'Deep leafy green' },
    ],
    story: 'Tourmaline grows in three-sided crystal columns with grooves running down the sides, like a tiny green skyscraper built by the Earth.',
    wow: 'Warm up a tourmaline and it becomes ELECTRIC — one end turns plus, the other minus, and it can attract dust like a magnet!',
  },
  {
    id: 'pinktourmaline', name: 'Pink Tourmaline', emoji: '🍉', pronounce: 'pink TOOR-ma-leen',
    accent: '#ff5fa2', swatch: ['#ff9ec9', '#f23d8a', '#8a1247'],
    cut: 'trigonal',
    refract: { color: '#ff66a8', ior: 1.62, aberration: 0.009, fresnel: 0.15, bounces: 3 },
    material: { color: 0xf23d8a, roughness: 0.03, transmission: 0.92, ior: 1.62, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🍉', label: 'Coolest trick', value: 'Can grow like a watermelon!' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil & California' },
      { icon: '🎨', label: 'Color', value: 'Bubblegum pink' },
    ],
    story: 'Pink Tourmaline grows in the same three-sided towers as its green brother — sometimes they even grow together in ONE crystal!',
    wow: 'Watermelon tourmaline is real: pink in the middle, green around the outside, just like a slice of watermelon. Nature did that on purpose!',
  },
  {
    id: 'peridot', name: 'Peridot', emoji: '🌋', pronounce: 'PAIR-ih-doh',
    accent: '#9acd32', swatch: ['#c4e86a', '#8ab821', '#42660a'],
    cut: 'rough',
    refract: { color: '#a8d93f', ior: 1.65, aberration: 0.01, fresnel: 0.15, bounces: 3 },
    material: { color: 0x8ab821, roughness: 0.04, transmission: 0.92, ior: 1.65, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'August' },
      { icon: '🗺️', label: 'Found in', value: 'Arizona, Egypt & lava!' },
      { icon: '🎨', label: 'Color', value: 'Lime green' },
    ],
    story: 'Peridot is born in fire — it forms deep inside the Earth and rides up in lava! Some Hawaiian beaches have green sand made of tiny peridots.',
    wow: 'Peridot also falls from SPACE — scientists have found real peridot crystals inside meteorites older than the Earth itself!',
  },
  {
    id: 'zircon', name: 'Zircon', emoji: '⏳', pronounce: 'ZUR-kon',
    accent: '#5fc8ff', swatch: ['#a8e2ff', '#4ab4f0', '#0f6499'],
    cut: 'bipyramid',
    refract: { color: '#73d0ff', ior: 1.93, aberration: 0.025, fresnel: 0.2, bounces: 3 },
    material: { color: 0x4ab4f0, roughness: 0.02, transmission: 0.95, ior: 1.93, thickness: 1.8, envMapIntensity: 1.5 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7.5 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'December (the old one!)' },
      { icon: '🗺️', label: 'Found in', value: 'Cambodia, Sri Lanka & Australia' },
      { icon: '🎨', label: 'Color', value: 'Electric blue' },
    ],
    story: 'Zircon sparkles with rainbow fire almost like a diamond! It is a real natural gem — don’t mix it up with fake “cubic zirconia”.',
    wow: 'Tiny zircon crystals from Australia are 4.4 BILLION years old — the oldest pieces of Earth ever found. Older than the Moon’s craters!',
  },
  {
    id: 'spinel', name: 'Spinel', emoji: '🎈', pronounce: 'spih-NEL',
    accent: '#ff2b4e', swatch: ['#ff7088', '#e8123a', '#800617'],
    cut: 'octa',
    refract: { color: '#ff3354', ior: 1.72, aberration: 0.011, fresnel: 0.18, bounces: 3 },
    material: { color: 0xe8123a, roughness: 0.02, transmission: 0.93, ior: 1.72, thickness: 1.8, envMapIntensity: 1.4 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'August (with peridot!)' },
      { icon: '🗺️', label: 'Found in', value: 'Myanmar & Vietnam' },
      { icon: '🎨', label: 'Color', value: 'Fiery red' },
    ],
    story: 'Spinel grows in perfect little pyramids stuck back-to-back, just like raw diamonds do. For centuries people thought red spinels WERE rubies!',
    wow: 'The giant “ruby” on the front of the British Crown is actually a spinel — it fooled kings and queens for 500 years!',
  },
  {
    id: 'alexandrite', name: 'Alexandrite', emoji: '🪄', pronounce: 'al-ex-AN-drite',
    accent: '#3ec9a7', swatch: ['#7fe8cd', '#2aa886', '#7a3df0'],
    cut: 'hexTab',
    refract: { color: '#45cfae', ior: 1.75, aberration: 0.011, fresnel: 0.18, bounces: 3 },
    material: { color: 0x2aa886, roughness: 0.02, transmission: 0.93, ior: 1.75, thickness: 1.8, envMapIntensity: 1.4 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8.5 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'June (with pearl!)' },
      { icon: '🗺️', label: 'Found in', value: 'Russia, Brazil & Sri Lanka' },
      { icon: '🎨', label: 'Color', value: 'Green by day, red by night!' },
    ],
    story: 'Alexandrite is the magician of gems: it is GREEN in daylight but turns RED-PURPLE under lamplight at night. Same stone, two colors!',
    wow: 'It was discovered in Russia on the birthday of Prince Alexander, the future tsar — that’s how it got its royal name.',
  },
  {
    id: 'tanzanite', name: 'Tanzanite', emoji: '🌌', pronounce: 'TAN-zuh-nite',
    accent: '#5a4fff', swatch: ['#9a8fff', '#4a3de8', '#1c1480'],
    cut: 'orthoPrism',
    refract: { color: '#6a5fff', ior: 1.7, aberration: 0.011, fresnel: 0.18, bounces: 3 },
    material: { color: 0x4a3de8, roughness: 0.02, transmission: 0.93, ior: 1.7, thickness: 1.8, envMapIntensity: 1.4 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '6.5 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'December (the new one!)' },
      { icon: '🗺️', label: 'Found in', value: 'ONLY Tanzania!' },
      { icon: '🎨', label: 'Color', value: 'Blue-violet twilight' },
    ],
    story: 'Tanzanite exists in only ONE place on Earth: a few square miles at the foot of Mount Kilimanjaro in Tanzania, Africa.',
    wow: 'Tanzanite is a thousand times rarer than diamond — and scientists think the mines may run empty in your lifetime, making it a true treasure!',
  },
  {
    id: 'iolite', name: 'Iolite', emoji: '🧭', pronounce: 'EYE-oh-lite',
    accent: '#4a5fd0', swatch: ['#8a9aee', '#3a4fc0', '#141f66'],
    cut: 'orthoPrism',
    refract: { color: '#5468d9', ior: 1.54, aberration: 0.008, fresnel: 0.15, bounces: 3 },
    material: { color: 0x3a4fc0, roughness: 0.03, transmission: 0.9, ior: 1.54, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '⛵', label: 'Known as', value: 'The Viking compass stone' },
      { icon: '🗺️', label: 'Found in', value: 'India, Madagascar & Wyoming' },
      { icon: '🎨', label: 'Color', value: 'Violet-blue' },
    ],
    story: 'Iolite is a color-trickster: look through it one way and it’s deep blue, turn it sideways and it goes almost clear!',
    wow: 'Legends say Viking sailors used thin slices of iolite as the world’s first sunglasses-compass, finding the hidden sun on cloudy days at sea!',
  },
  {
    id: 'apatite', name: 'Apatite', emoji: '🦷', pronounce: 'AP-uh-tite',
    accent: '#2ec4b6', swatch: ['#6fe3d8', '#1fab9e', '#0a5c54'],
    cut: 'hexColumn',
    refract: { color: '#35ccbe', ior: 1.63, aberration: 0.009, fresnel: 0.15, bounces: 3 },
    material: { color: 0x1fab9e, roughness: 0.03, transmission: 0.92, ior: 1.63, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '5 out of 10' },
      { icon: '🦷', label: 'Fun family', value: 'Same stuff as your teeth!' },
      { icon: '🗺️', label: 'Found in', value: 'Madagascar, Mexico & Brazil' },
      { icon: '🎨', label: 'Color', value: 'Tropical sea teal' },
    ],
    story: 'Apatite comes in electric ocean blues and greens that look almost too bright to be real. It grows in little six-sided columns.',
    wow: 'Your TEETH and BONES are made of apatite! Your body grows this mineral all by itself — you are part crystal!',
  },
  {
    id: 'fluorite', name: 'Fluorite', emoji: '🟩', pronounce: 'FLOOR-ite',
    accent: '#7ddc6f', swatch: ['#b08fff', '#5fd957', '#1f7a99'],
    cut: 'cube',
    refract: { color: '#86df7a', ior: 1.43, aberration: 0.006, fresnel: 0.15, bounces: 3 },
    material: { color: 0x5fd957, roughness: 0.03, transmission: 0.93, ior: 1.43, thickness: 1.8, envMapIntensity: 1.2 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '4 out of 10' },
      { icon: '🔦', label: 'Super power', value: 'Glows under black light!' },
      { icon: '🗺️', label: 'Found in', value: 'China, Mexico & Illinois' },
      { icon: '🎨', label: 'Color', value: 'Green, purple & rainbow' },
    ],
    story: 'Fluorite grows perfect glassy CUBES all by itself — no machines needed! It comes in green, purple, blue, even rainbow-striped.',
    wow: 'Shine a black light on fluorite and it GLOWS — the word “fluorescent” was invented because of this very stone!',
  },
  {
    id: 'kunzite', name: 'Kunzite', emoji: '🌷', pronounce: 'KOONTS-ite',
    accent: '#ff9fd0', swatch: ['#ffc9e4', '#f57ab8', '#a8336f'],
    cut: 'orthoPrism',
    refract: { color: '#ffabd6', ior: 1.66, aberration: 0.009, fresnel: 0.18, bounces: 3 },
    material: { color: 0xf57ab8, roughness: 0.03, transmission: 0.93, ior: 1.66, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🌙', label: 'Special rule', value: 'Loves the dark, fades in sun' },
      { icon: '🗺️', label: 'Found in', value: 'Afghanistan, Brazil & California' },
      { icon: '🎨', label: 'Color', value: 'Lilac pink' },
    ],
    story: 'Kunzite is a dreamy pink crystal named after George Kunz, a gem hunter who started collecting stones when he was just a kid!',
    wow: 'Kunzite is called an “evening gem” — if it sits in hot sunshine too long, its pink color slowly fades away. It keeps its best color in the dark!',
  },
  {
    id: 'painite', name: 'Painite', emoji: '🏆', pronounce: 'PAYN-ite',
    accent: '#c2542e', swatch: ['#e08a5c', '#a8431f', '#521c0a'],
    cut: 'hexColumn',
    refract: { color: '#c75c33', ior: 1.79, aberration: 0.011, fresnel: 0.15, bounces: 3 },
    material: { color: 0xa8431f, roughness: 0.03, transmission: 0.88, ior: 1.79, thickness: 1.8, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '🥇', label: 'World record', value: 'Once the rarest mineral ever' },
      { icon: '🗺️', label: 'Found in', value: 'Myanmar' },
      { icon: '🎨', label: 'Color', value: 'Reddish brown' },
    ],
    story: 'Painite held a world record: for 50 years, only TWO crystals existed on the whole planet. Museums guarded them like dragon treasure!',
    wow: 'The Guinness Book of Records once named painite the rarest mineral on Earth — rarer than anything in any pirate’s chest!',
  },
  {
    id: 'pyrite', name: 'Pyrite', emoji: '🥸', pronounce: 'PY-rite',
    accent: '#e8c14d', swatch: ['#f5d97a', '#c79a2e', '#6e500e'],
    cut: 'cube',
    material: { color: 0xd9b143, roughness: 0.32, metalness: 1.0, envMapIntensity: 1.2 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '6 out of 10' },
      { icon: '🤥', label: 'Nickname', value: '“Fool’s Gold”' },
      { icon: '🗺️', label: 'Found in', value: 'Spain, Peru & everywhere' },
      { icon: '🎨', label: 'Color', value: 'Shiny fake gold' },
    ],
    story: 'Pyrite grows PERFECT shiny metal cubes straight out of the rock — corners sharp as dice, no polishing needed. Nature is showing off!',
    wow: 'It’s called Fool’s Gold because it tricked gold miners — but strike it hard and it makes SPARKS! Its name comes from the Greek word for fire.',
  },
  {
    id: 'hematite', name: 'Hematite', emoji: '🪞', pronounce: 'HEE-ma-tite',
    accent: '#9aa3ad', swatch: ['#c4ccd4', '#6e7780', '#23282e'],
    cut: 'bubbles',
    material: { color: 0x5c646c, roughness: 0.22, metalness: 1.0, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '6 out of 10' },
      { icon: '🔴', label: 'Made of', value: 'Iron — like a magnet!' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil, England & Michigan' },
      { icon: '🎨', label: 'Color', value: 'Mirror silver-gray' },
    ],
    story: 'Hematite grows in shiny silver bubbles that look like metal balloons. Polish it and it turns into a real stone mirror!',
    wow: 'Mars is the Red Planet because of hematite dust! Scratch silvery hematite and the streak is always RED — it is an iron rust stone.',
  },
  {
    id: 'moonstone', name: 'Moonstone', emoji: '🌕', pronounce: 'MOON-stohn',
    accent: '#bcd4f0', swatch: ['#f0f5fc', '#bcd4f0', '#7a93b8'],
    cut: 'rough',
    material: { color: 0xe8eef7, roughness: 0.3, transmission: 0.45, ior: 1.52, thickness: 2.2, iridescence: 0.5, iridescenceIOR: 1.3, iridescenceThicknessRange: [120, 400], clearcoat: 0.8, clearcoatRoughness: 0.2, envMapIntensity: 1.1 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '6 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'June' },
      { icon: '🗺️', label: 'Found in', value: 'Sri Lanka & India' },
      { icon: '🎨', label: 'Color', value: 'Glowing moonlight blue' },
    ],
    story: 'Moonstone has a ghostly blue glow that floats across the stone when you tilt it, like moonlight gliding over water.',
    wow: 'Ancient Romans believed moonstone was made of frozen moonbeams. The glow even has a magical name: “adularescence”!',
  },
  {
    id: 'labradorite', name: 'Labradorite', emoji: '🦚', pronounce: 'LAB-ra-dor-ite',
    accent: '#3e9ea8', swatch: ['#5fc4ce', '#2a6e8a', '#1c2630'],
    cut: 'slab',
    material: { color: 0x39424d, roughness: 0.25, metalness: 0.1, iridescence: 1.0, iridescenceIOR: 1.6, iridescenceThicknessRange: [200, 900], clearcoat: 0.9, clearcoatRoughness: 0.15, envMapIntensity: 1.4 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '6 out of 10' },
      { icon: '🌌', label: 'Legend says', value: 'Northern Lights inside!' },
      { icon: '🗺️', label: 'Found in', value: 'Labrador, Canada & Madagascar' },
      { icon: '🎨', label: 'Color', value: 'Peacock flash on gray' },
    ],
    story: 'Labradorite looks like a plain gray rock — until light hits it and WHOOSH: electric blue, green and gold flames flash across it!',
    wow: 'An Inuit legend says the Northern Lights were once trapped inside these stones, and a warrior set them free with his spear — but some light stayed behind!',
  },
  {
    id: 'sunstone', name: 'Sunstone', emoji: '🌞', pronounce: 'SUN-stohn',
    accent: '#ff8c42', swatch: ['#ffc285', '#f2762e', '#993f0d'],
    cut: 'rough', fx: { type: 'flecks', colors: ['#ffb366', '#ff8533', '#ffd699'], count: 160, intensity: 0.4 },
    material: { color: 0xe8732e, roughness: 0.3, transmission: 0.35, ior: 1.52, thickness: 2.0, clearcoat: 0.7, clearcoatRoughness: 0.2, envMapIntensity: 1.2 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🏅', label: 'Famous as', value: 'Oregon’s state gem' },
      { icon: '🗺️', label: 'Found in', value: 'Oregon, Norway & India' },
      { icon: '🎨', label: 'Color', value: 'Glittery orange' },
    ],
    story: 'Sunstone sparkles from the inside out — it is filled with millions of tiny copper flakes that flash like a campfire when you turn it.',
    wow: 'In Oregon you can visit a real mine and dig for your OWN sunstones — and keep whatever you find!',
  },
  {
    id: 'turquoise', name: 'Turquoise', emoji: '🏜️', pronounce: 'TUR-koyz',
    accent: '#30c9b0', swatch: ['#6fe0cc', '#1fa893', '#0a5c50'],
    cut: 'nodule', fx: { type: 'spots', bg: '#26b8a5', colors: ['#8a6a4a', '#1a8577', '#5c4632'], count: 30, rMin: 3, rMax: 14 },
    material: { color: 0xffffff, roughness: 0.5, clearcoat: 0.4, clearcoatRoughness: 0.3, envMapIntensity: 0.9 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '5 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'December (the classic!)' },
      { icon: '🗺️', label: 'Found in', value: 'Arizona, Iran & Egypt' },
      { icon: '🎨', label: 'Color', value: 'Desert sky blue' },
    ],
    story: 'Turquoise is one of the very FIRST gems humans ever dug up — miners in Egypt were collecting it over 6,000 years ago!',
    wow: 'The brown squiggly lines on turquoise are called the “spider web” — they are pieces of the mother rock it grew inside.',
  },
  {
    id: 'lapis', name: 'Lapis Lazuli', emoji: '⭐', pronounce: 'LAP-iss LAZ-oo-lee',
    accent: '#2e5cd9', swatch: ['#5c85f0', '#1d3fa8', '#0a1c52'],
    cut: 'rough', fx: { type: 'flecks', colors: ['#f5c542', '#ffe28a'], count: 80, intensity: 0.5 },
    material: { color: 0x1d3fa8, roughness: 0.4, clearcoat: 0.5, clearcoatRoughness: 0.25, envMapIntensity: 1.0 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '5 out of 10' },
      { icon: '🎨', label: 'Super power', value: 'Became famous blue paint!' },
      { icon: '🗺️', label: 'Found in', value: 'Afghanistan (for 6,000 years!)' },
      { icon: '🎨', label: 'Color', value: 'Night-sky blue, gold stars' },
    ],
    story: 'Lapis Lazuli is deep night-sky blue with golden pyrite sparkles inside, like a piece of the starry sky you can hold.',
    wow: 'Long ago, lapis was crushed into the world’s most expensive blue paint — more costly than gold! King Tut’s famous golden mask has lapis eyebrows.',
  },
  {
    id: 'malachite', name: 'Malachite', emoji: '🐍', pronounce: 'MAL-uh-kite',
    accent: '#1f9e54', swatch: ['#36c277', '#0e7a3d', '#053920'],
    cut: 'bubbles', fx: { type: 'rings', colors: ['#0e5c30', '#1f9e54', '#0a3d20', '#36c277', '#116e38'] },
    material: { color: 0xffffff, roughness: 0.3, clearcoat: 0.8, clearcoatRoughness: 0.2, envMapIntensity: 1.0 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '4 out of 10' },
      { icon: '🧪', label: 'Made by', value: 'Copper turning green' },
      { icon: '🗺️', label: 'Found in', value: 'Congo, Russia & Arizona' },
      { icon: '🎨', label: 'Color', value: 'Swirly green stripes' },
    ],
    story: 'Malachite grows in bubbly green bumps with dark and light stripes swirling through every bubble — no two pieces ever match.',
    wow: 'Malachite is made when copper slowly rusts green — the same reason the Statue of Liberty is green! Egyptians ground it up for eye makeup.',
  },
  {
    id: 'azurite', name: 'Azurite', emoji: '🌀', pronounce: 'AZH-ur-ite',
    accent: '#2456e8', swatch: ['#4d7aff', '#1437b3', '#060f47'],
    cut: 'nodule',
    material: { color: 0x1437b3, roughness: 0.35, clearcoat: 0.7, clearcoatRoughness: 0.2, envMapIntensity: 1.1 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '4 out of 10' },
      { icon: '🔄', label: 'Magic trick', value: 'Slowly turns into malachite!' },
      { icon: '🗺️', label: 'Found in', value: 'Arizona, Namibia & France' },
      { icon: '🎨', label: 'Color', value: 'Deepest electric blue' },
    ],
    story: 'Azurite is malachite’s electric-blue twin — they are both copper stones and often grow hugging each other in the same rock.',
    wow: 'Azurite is a shape-shifter: over many years it can slowly transform itself into green malachite, atom by atom!',
  },
  {
    id: 'jade', name: 'Jade', emoji: '🐉', pronounce: 'JAYD',
    accent: '#3da06b', swatch: ['#6fc795', '#2e8b57', '#11472b'],
    cut: 'rough',
    material: { color: 0x2e8b57, roughness: 0.25, transmission: 0.35, ior: 1.66, thickness: 2.4, attenuationColor: 0x2e8b57, attenuationDistance: 1.4, clearcoat: 0.9, clearcoatRoughness: 0.12, envMapIntensity: 1.1 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10 (and super strong!)' },
      { icon: '🐲', label: 'Loved by', value: 'Chinese emperors for 5,000 years' },
      { icon: '🗺️', label: 'Found in', value: 'Myanmar, China & Guatemala' },
      { icon: '🎨', label: 'Color', value: 'Dragon green' },
    ],
    story: 'Jade is the emperor’s stone — in ancient China it was worth MORE than gold, and emperors were even buried in suits made of jade!',
    wow: 'Jade is so tough it almost never breaks — ancient people made axes from it. Its secret: billions of tiny crystals woven together like fabric!',
  },
  {
    id: 'amber', name: 'Amber', emoji: '🦟', pronounce: 'AM-ber',
    accent: '#ffb340', swatch: ['#ffd485', '#f59824', '#8f4d05'],
    cut: 'nodule',
    material: { color: 0xffa726, roughness: 0.12, transmission: 0.92, ior: 1.54, thickness: 2.2, attenuationColor: 0xf57c00, attenuationDistance: 1.6, clearcoat: 1.0, clearcoatRoughness: 0.1, envMapIntensity: 1.2 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '2 out of 10 (it’s soft!)' },
      { icon: '🌲', label: 'What is it?', value: 'Fossil tree sap!' },
      { icon: '🗺️', label: 'Found in', value: 'Baltic Sea beaches & Dominican Republic' },
      { icon: '🎨', label: 'Color', value: 'Golden honey' },
    ],
    story: 'Amber isn’t a rock at all — it’s sticky tree sap that hardened and fossilized for MILLIONS of years until it turned to golden treasure.',
    wow: 'Some amber has real prehistoric bugs frozen inside — mosquitoes and ants that got stuck in the sap when dinosaurs were alive!',
  },
  {
    id: 'pearl', name: 'Pearl', emoji: '🦪', pronounce: 'PURL',
    accent: '#f0e6da', swatch: ['#fdf8f0', '#e8dcc9', '#b3a48c'],
    cut: 'sphere',
    material: { color: 0xfdf6ee, roughness: 0.22, iridescence: 0.65, iridescenceIOR: 1.3, iridescenceThicknessRange: [100, 500], clearcoat: 1.0, clearcoatRoughness: 0.18, envMapIntensity: 1.1 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '3 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'June' },
      { icon: '🗺️', label: 'Found in', value: 'Oceans, rivers & oyster farms' },
      { icon: '🎨', label: 'Color', value: 'Shimmery white' },
    ],
    story: 'Pearl is the only gem made by a living animal! When a tiny speck sneaks inside an oyster, the oyster wraps it in layer after layer of shiny pearl.',
    wow: 'It can take an oyster several YEARS to finish one pearl — thousands of layers thinner than paper, wrapped like the world’s slowest birthday present!',
  },
  {
    id: 'jet', name: 'Jet', emoji: '🪵', pronounce: 'JET',
    accent: '#8c8c8c', swatch: ['#3d3d3d', '#141414', '#000000'],
    cut: 'rough',
    material: { color: 0x0d0d0d, roughness: 0.35, clearcoat: 0.9, clearcoatRoughness: 0.2, envMapIntensity: 0.7 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '3 out of 10' },
      { icon: '🌳', label: 'What is it?', value: 'Fossil driftwood!' },
      { icon: '🗺️', label: 'Found in', value: 'Whitby, England & Spain' },
      { icon: '🎨', label: 'Color', value: '“Jet black”!' },
    ],
    story: 'Jet is ancient driftwood that sank to the sea floor millions of years ago and got squashed into smooth black gem-wood.',
    wow: 'When something is super dark we say it’s “jet black” — that saying comes from THIS very stone! It is so light it almost floats.',
  },
  {
    id: 'rhodochrosite', name: 'Rhodochrosite', emoji: '🍓', pronounce: 'roh-doh-KROH-site',
    accent: '#ff6f9c', swatch: ['#ffadc7', '#f04d80', '#8f1c45'],
    cut: 'nodule', fx: { type: 'rings', colors: ['#ff6f9c', '#ffd1e0', '#ff8fb3', '#f04d80', '#ffc2d6'] },
    material: { color: 0xffffff, roughness: 0.3, clearcoat: 0.7, clearcoatRoughness: 0.2, envMapIntensity: 1.0 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '4 out of 10' },
      { icon: '🏔️', label: 'Nickname', value: '“Inca Rose”' },
      { icon: '🗺️', label: 'Found in', value: 'Argentina & Colorado' },
      { icon: '🎨', label: 'Color', value: 'Raspberry & cream stripes' },
    ],
    story: 'Rhodochrosite looks like raspberry ripple ice cream turned to stone — bright pink with creamy white stripes curling through it.',
    wow: 'The Incas believed these stones were the hearts of their ancestors turned to rock — that’s why it’s called the Inca Rose!',
  },
  {
    id: 'rhodonite', name: 'Rhodonite', emoji: '⚡', pronounce: 'ROH-don-ite',
    accent: '#e85c8a', swatch: ['#f59ab8', '#d13d6e', '#2e1226'],
    cut: 'rough', fx: { type: 'spots', bg: '#d8537e', colors: ['#1a1a1a', '#2e2e2e', '#e88aa8'], count: 40, rMin: 4, rMax: 18 },
    material: { color: 0xffffff, roughness: 0.4, clearcoat: 0.5, clearcoatRoughness: 0.25, envMapIntensity: 0.9 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '6 out of 10' },
      { icon: '🇷🇺', label: 'Famous in', value: 'Russian palaces' },
      { icon: '🗺️', label: 'Found in', value: 'Russia, Australia & Massachusetts' },
      { icon: '🎨', label: 'Color', value: 'Pink with black lightning' },
    ],
    story: 'Rhodonite is rose-pink stone covered in black zig-zag veins, like little lightning bolts frozen in candy.',
    wow: 'Russian tsars loved rhodonite so much they made giant palace columns and even a 7-ton tomb from it!',
  },
  {
    id: 'sodalite', name: 'Sodalite', emoji: '📘', pronounce: 'SOH-da-lite',
    accent: '#3a5fc0', swatch: ['#7a93e0', '#2a4aa8', '#0e1c52'],
    cut: 'rough', fx: { type: 'spots', bg: '#2a4aa8', colors: ['#ffffff', '#d9e2f5', '#1d3585'], count: 35, rMin: 4, rMax: 20 },
    material: { color: 0xffffff, roughness: 0.45, clearcoat: 0.4, clearcoatRoughness: 0.3, envMapIntensity: 0.9 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '6 out of 10' },
      { icon: '🥤', label: 'Named after', value: 'Sodium (like soda!)' },
      { icon: '🗺️', label: 'Found in', value: 'Canada, Brazil & Greenland' },
      { icon: '🎨', label: 'Color', value: 'Royal blue, white veins' },
    ],
    story: 'Sodalite is royal blue with white rivers running through it. A giant load of it was found in Canada while a princess was visiting — so they named the mine after her!',
    wow: 'Some sodalite has a secret: under a black light, certain pieces glow bright ORANGE like embers!',
  },
  {
    id: 'larimar', name: 'Larimar', emoji: '🏝️', pronounce: 'LAR-ih-mar',
    accent: '#4dc4d9', swatch: ['#a8e8f0', '#45b8cf', '#147a91'],
    cut: 'nodule', fx: { type: 'spots', bg: '#45b8cf', colors: ['#e8f8fa', '#8adfe8', '#1f93ab'], count: 60, rMin: 8, rMax: 30 },
    material: { color: 0xffffff, roughness: 0.35, clearcoat: 0.6, clearcoatRoughness: 0.2, envMapIntensity: 1.0 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '5 out of 10' },
      { icon: '🌴', label: 'How rare?', value: 'ONE mountain on Earth!' },
      { icon: '🗺️', label: 'Found in', value: 'Only the Dominican Republic!' },
      { icon: '🎨', label: 'Color', value: 'Caribbean sea ripples' },
    ],
    story: 'Larimar looks exactly like sunlight dancing on Caribbean waves — and it is found in only ONE mountain in the Dominican Republic and nowhere else on Earth.',
    wow: 'The man who named it mixed his daughter’s name, Larissa, with “mar” — the Spanish word for sea. Larissa + mar = Larimar!',
  },
  {
    id: 'kyanite', name: 'Kyanite', emoji: '🗡️', pronounce: 'KY-uh-nite',
    accent: '#4d7ae0', swatch: ['#8aa8f0', '#3a63cc', '#122a70'],
    cut: 'slab', fx: { type: 'stripes', colors: ['#3a63cc', '#5c85e8', '#24449e', '#7a9af0', '#2e52b8'] },
    material: { color: 0xffffff, roughness: 0.2, transmission: 0.35, ior: 1.72, thickness: 1.6, clearcoat: 0.8, clearcoatRoughness: 0.15, envMapIntensity: 1.2 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '4 AND 7 — both at once!' },
      { icon: '🤺', label: 'Special look', value: 'Grows in blue blades' },
      { icon: '🗺️', label: 'Found in', value: 'Nepal, Brazil & the Alps' },
      { icon: '🎨', label: 'Color', value: 'Sword blue' },
    ],
    story: 'Kyanite grows in long flat blades like blue crystal swords, with light and dark stripes running down each blade.',
    wow: 'Kyanite has a superpower no other gem has: scratch it ALONG the blade and it’s soft, scratch it ACROSS and it’s hard. Two toughness scores in one stone!',
  },
  {
    id: 'selenite', name: 'Selenite', emoji: '🌙', pronounce: 'SEL-en-ite',
    accent: '#e8ecf2', swatch: ['#ffffff', '#e0e6ee', '#9aa6b8'],
    cut: 'hexColumn',
    material: { color: 0xf2f5f9, roughness: 0.38, transmission: 0.7, ior: 1.52, thickness: 2.0, attenuationColor: 0xe8edf5, attenuationDistance: 1.8, clearcoat: 0.5, clearcoatRoughness: 0.3, envMapIntensity: 1.0 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '2 out of 10 — softest here!' },
      { icon: '🌙', label: 'Named after', value: 'Selene, the moon goddess' },
      { icon: '🗺️', label: 'Found in', value: 'Mexico, Morocco & Utah' },
      { icon: '🎨', label: 'Color', value: 'Glowing pearly white' },
    ],
    story: 'Selenite is a pearly white crystal so soft you could scratch it with your fingernail. It glows softly when light passes through, like frozen moonlight.',
    wow: 'In Mexico there is a Cave of Crystals where selenite grew as big as SCHOOL BUSES — the biggest crystals ever found on Earth, 39 feet long!',
  },
  {
    id: 'celestite', name: 'Celestite', emoji: '☁️', pronounce: 'SEL-es-tite',
    accent: '#9ec4f0', swatch: ['#cfe2fa', '#8ab4e8', '#4a78b3'],
    cut: 'cluster',
    material: { color: 0xb8d4f5, roughness: 0.08, transmission: 0.85, ior: 1.62, thickness: 1.6, attenuationColor: 0x9ec4f0, attenuationDistance: 2.0, clearcoat: 0.6, clearcoatRoughness: 0.1, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '3 out of 10' },
      { icon: '👼', label: 'Name means', value: '“Heavenly” in Latin' },
      { icon: '🗺️', label: 'Found in', value: 'Madagascar & Ohio' },
      { icon: '🎨', label: 'Color', value: 'Pale heaven blue' },
    ],
    story: 'Celestite grows clouds of pale blue crystals inside hollow rocks — open one up and it looks like a tiny sky made of glass.',
    wow: 'On an island in Lake Erie, Ohio, there is a celestite geode SO big that people climb inside it — it’s the world’s largest geode and it used to be a swimming hole cave!',
  },
  {
    id: 'ammolite', name: 'Ammolite', emoji: '🐚', pronounce: 'AM-oh-lite',
    accent: '#ff5c3a', swatch: ['#ff8a3d', '#38c172', '#7a4dff'],
    cut: 'slab', fx: { type: 'flecks', colors: ['#ff3a2e', '#ffa01f', '#2ee65c', '#1f9dff', '#b34dff'], count: 200, intensity: 0.55 },
    material: { color: 0x5c3a1e, roughness: 0.25, iridescence: 1.0, iridescenceIOR: 1.52, iridescenceThicknessRange: [150, 800], clearcoat: 1.0, clearcoatRoughness: 0.12, envMapIntensity: 1.3 },
    chips: [
      { icon: '💪', label: 'Toughness', value: '4 out of 10' },
      { icon: '🦕', label: 'What is it?', value: 'A dinosaur-age seashell!' },
      { icon: '🗺️', label: 'Found in', value: 'Alberta, Canada' },
      { icon: '🎨', label: 'Color', value: 'Every color, all at once' },
    ],
    story: 'Ammolite is a FOSSIL gem — the rainbow shell of sea creatures called ammonites that swam when dinosaurs walked the Earth, 70 million years ago.',
    wow: 'Ammolite is one of the newest official gems ever — and the Blackfoot people call it the Buffalo Stone and have treasured it for centuries!',
  },
];
