// Gem data: facts written for a 6-year-old, material params for Three.js MeshPhysicalMaterial
export const GEMS = [
  {
    id: 'obsidian',
    name: 'Black Obsidian',
    emoji: '🌋',
    pronounce: 'ob-SID-ee-un',
    accent: '#3dd68c',
    swatch: ['#3b3f46', '#101216', '#000000'],
    cut: 'chunk',
    fx: 'ripple',
    material: {
      color: 0x050507, roughness: 0.08, metalness: 0.0,
      transmission: 0.12, ior: 1.5, thickness: 2.2,
      clearcoat: 1.0, clearcoatRoughness: 0.04,
      attenuationColor: 0x16241a, attenuationDistance: 0.7,
      envMapIntensity: 0.45,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '5 out of 10' },
      { icon: '🌋', label: 'What is it?', value: 'Volcano glass!' },
      { icon: '🗺️', label: 'Found in', value: 'Mexico, Iceland & the USA' },
      { icon: '🎨', label: 'Color', value: 'Shiny black' },
    ],
    story: 'Black Obsidian is nature’s glass! When a volcano erupts, super-hot lava sometimes cools down SO fast that it freezes into shiny black glass before any crystals can grow.',
    wow: 'Obsidian can be sharper than a doctor’s scalpel! Long, long ago, people made arrowheads and knives out of it.',
  },
  {
    id: 'diamond',
    name: 'Diamond',
    emoji: '💎',
    pronounce: 'DY-mund',
    accent: '#bfe3ff',
    swatch: ['#ffffff', '#cfe8ff', '#8fb8e8'],
    cut: 'brilliant',
    material: {
      color: 0xffffff, roughness: 0.0, metalness: 0.0,
      transmission: 1.0, ior: 2.42, thickness: 1.6, dispersion: 0.35,
      clearcoat: 1.0, clearcoatRoughness: 0.0,
      envMapIntensity: 1.8,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '10 out of 10 — the champ!' },
      { icon: '🎂', label: 'Birthstone', value: 'April' },
      { icon: '🗺️', label: 'Found in', value: 'Deep, deep underground' },
      { icon: '🎨', label: 'Color', value: 'Clear like ice' },
    ],
    story: 'Diamond is the hardest natural thing on Earth! It grows super deep underground where it is very hot and very squished, and volcanoes carry it up to us.',
    wow: 'Diamonds are made of the exact same stuff as a pencil tip — carbon! Squeezing it for billions of years makes it sparkly instead of scribbly.',
  },
  {
    id: 'ruby',
    name: 'Ruby',
    emoji: '❤️',
    pronounce: 'ROO-bee',
    accent: '#ff4d6d',
    swatch: ['#ff7a93', '#e6173f', '#7c0220'],
    cut: 'brilliant',
    material: {
      emissive: 0xcc0a33, emissiveIntensity: 0.3,
      color: 0xff4060, roughness: 0.02, metalness: 0.0,
      transmission: 0.95, ior: 1.77, thickness: 1.8, dispersion: 0.12,
      attenuationColor: 0xe61745, attenuationDistance: 2.5,
      clearcoat: 0.6, clearcoatRoughness: 0.05,
      envMapIntensity: 1.5,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '9 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'July' },
      { icon: '🗺️', label: 'Found in', value: 'Myanmar, Thailand & Africa' },
      { icon: '🎨', label: 'Color', value: 'Fire-engine red' },
    ],
    story: 'Ruby is the king of red gems! A tiny pinch of an ingredient called chromium sneaks inside and paints the whole crystal red.',
    wow: 'Rubies and sapphires are secretly the SAME mineral. If it’s red, we call it a ruby. Any other color? That’s a sapphire!',
  },
  {
    id: 'sapphire',
    name: 'Sapphire',
    emoji: '💙',
    pronounce: 'SAF-ire',
    accent: '#4d7cff',
    swatch: ['#7da2ff', '#1f4fd8', '#0a1f6b'],
    cut: 'brilliant',
    material: {
      emissive: 0x1335cc, emissiveIntensity: 0.3,
      color: 0x3f6fff, roughness: 0.02, metalness: 0.0,
      transmission: 0.95, ior: 1.77, thickness: 1.8, dispersion: 0.12,
      attenuationColor: 0x1f4fd8, attenuationDistance: 2.5,
      clearcoat: 0.6, clearcoatRoughness: 0.05,
      envMapIntensity: 1.5,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '9 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'September' },
      { icon: '🗺️', label: 'Found in', value: 'Sri Lanka, Australia & Montana' },
      { icon: '🎨', label: 'Color', value: 'Deep ocean blue' },
    ],
    story: 'Sapphire is ruby’s blue brother! It is so tough that some watch glass and even spaceship windows are made from grown sapphire.',
    wow: 'Sapphires come in almost EVERY color — blue, pink, yellow, green, even rainbow party colors. Every color except red!',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    emoji: '💚',
    pronounce: 'EM-er-uld',
    accent: '#19c37d',
    swatch: ['#4fe3a4', '#0ca860', '#03522d'],
    cut: 'emerald',
    material: {
      emissive: 0x078a4c, emissiveIntensity: 0.3,
      color: 0x17b06b, roughness: 0.03, metalness: 0.0,
      transmission: 0.92, ior: 1.57, thickness: 2.0, dispersion: 0.08,
      attenuationColor: 0x0a9a57, attenuationDistance: 1.9,
      clearcoat: 0.5, clearcoatRoughness: 0.08,
      envMapIntensity: 0.9,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '8 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'May' },
      { icon: '🗺️', label: 'Found in', value: 'Colombia, Zambia & Brazil' },
      { icon: '🎨', label: 'Color', value: 'Jungle green' },
    ],
    story: 'Emerald is the green superstar of gems. It grows slowly in cracks deep in the mountains, and people have treasured it for thousands of years.',
    wow: 'Most emeralds have a tiny “garden” inside — little squiggly marks that prove the gem grew all by itself in nature!',
  },
  {
    id: 'amethyst',
    name: 'Amethyst',
    emoji: '💜',
    pronounce: 'AM-uh-thist',
    accent: '#a06bff',
    swatch: ['#c79bff', '#8a4dff', '#3d1680'],
    cut: 'cluster',
    material: {
      emissive: 0x7a3df0, emissiveIntensity: 0.32,
      color: 0xa570ff, roughness: 0.05, metalness: 0.0,
      transmission: 0.92, ior: 1.55, thickness: 1.8, dispersion: 0.06,
      attenuationColor: 0x8a4dff, attenuationDistance: 2.6,
      clearcoat: 0.4, clearcoatRoughness: 0.1,
      envMapIntensity: 1.4,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'February' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil & Uruguay' },
      { icon: '🎨', label: 'Color', value: 'Royal purple' },
    ],
    story: 'Amethyst is purple quartz that grows in pointy crystal towers. It loves to grow inside hollow rocks, packed together like a crystal city.',
    wow: 'Amethyst grows inside secret rocks called geodes — boring and bumpy on the outside, but crack one open and it’s FULL of purple crystals!',
  },
  {
    id: 'citrine',
    name: 'Citrine',
    emoji: '🍋',
    pronounce: 'SIH-treen',
    accent: '#ffb321',
    swatch: ['#ffd97a', '#ff9d1f', '#9c5400'],
    cut: 'point',
    material: {
      emissive: 0xb86a00, emissiveIntensity: 0.2,
      color: 0xffa01f, roughness: 0.04, metalness: 0.0,
      transmission: 0.95, ior: 1.55, thickness: 1.8, dispersion: 0.06,
      attenuationColor: 0xff8c00, attenuationDistance: 1.8,
      clearcoat: 0.4, clearcoatRoughness: 0.1,
      envMapIntensity: 1.4,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'November' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil' },
      { icon: '🎨', label: 'Color', value: 'Sunny gold' },
    ],
    story: 'Citrine is amethyst’s sunny cousin — the same crystal, but heated up until it turns golden like honey and sunshine.',
    wow: 'Citrine is named after “citron”, the French word for lemon, because it looks like frozen lemonade!',
  },
  {
    id: 'rosequartz',
    name: 'Rose Quartz',
    emoji: '🌸',
    pronounce: 'rohz KWORTS',
    accent: '#ff9ec7',
    swatch: ['#ffd2e4', '#ff9ec7', '#c75e8e'],
    cut: 'cabochon',
    fx: 'cloudy',
    material: {
      emissive: 0xc4647e, emissiveIntensity: 0.12,
      color: 0xffb3cf, roughness: 0.35, metalness: 0.0,
      transmission: 0.85, ior: 1.55, thickness: 2.6,
      attenuationColor: 0xff9ec7, attenuationDistance: 1.2,
      clearcoat: 0.8, clearcoatRoughness: 0.2,
      envMapIntensity: 1.2,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '7 out of 10' },
      { icon: '💗', label: 'Known as', value: 'The friendship stone' },
      { icon: '🗺️', label: 'Found in', value: 'Brazil, Madagascar & South Dakota' },
      { icon: '🎨', label: 'Color', value: 'Soft pink' },
    ],
    story: 'Rose Quartz is a soft pink, cloudy crystal. People all over the world call it the stone of friendship and kind hearts.',
    wow: 'Some special rose quartz hides a glowing six-pointed STAR inside that only appears when light shines on it just right!',
  },
  {
    id: 'opal',
    name: 'Opal',
    emoji: '🌈',
    pronounce: 'OH-pul',
    accent: '#7fe8e0',
    swatch: ['#ffffff', '#bdf3ec', '#caa6ff'],
    cut: 'cabochon',
    fx: 'opal',
    material: {
      emissive: 0x8fd8cc, emissiveIntensity: 0.08,
      color: 0xf2f6f5, roughness: 0.25, metalness: 0.0,
      transmission: 0.7, ior: 1.45, thickness: 2.4,
      attenuationColor: 0xd9fff7, attenuationDistance: 1.5,
      iridescence: 1.0, iridescenceIOR: 1.3, iridescenceThicknessRange: [120, 700],
      clearcoat: 1.0, clearcoatRoughness: 0.15,
      envMapIntensity: 1.3,
    },
    chips: [
      { icon: '💪', label: 'Toughness', value: '6 out of 10' },
      { icon: '🎂', label: 'Birthstone', value: 'October' },
      { icon: '🗺️', label: 'Found in', value: 'Australia (almost all of them!)' },
      { icon: '🎨', label: 'Color', value: 'Rainbow flashes' },
    ],
    story: 'Opal is the rainbow gem! It is made from tiny, tiny balls of silica with real water trapped inside, and they bounce light into every color you can imagine.',
    wow: 'NASA robots found opal on MARS! And every opal has a little bit of real water inside it.',
  },
];
